volumes:
  royalpong_data:

networks:
  backend:

services:
  backend:
    build: ./backend
    container_name: backendC
    env_file: .env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./backend:/app
  
  frontend:
    build: 
      context: ./frontend
    container_name: frontendC
    env_file: .env
    ports:
      - 4242:4242
    restart: always
    networks:
      - backend
    volumes:
      - ./frontend:/app

  # nginx:
  #   build: ./nginx
  #   container_name: nginxC
  #   env_file: .env
  #   depends_on: 
  #     - frontnew
  #   ports:
  #     - target: 80
  #       published: 80
  #       protocol: tcp
  #       mode: host
  #   restart: always
  #   networks:
  #     - backend
  #   volumes:
  #     - ./frontnew:/app

  postgres:
    image: postgres:16beta1-alpine3.18
    container_name: postgresC
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - royalpong_data:/var/lib/postgresql/data/
    networks:
      - backend

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminerC
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

